[env:esp32-c6-gateway]
; TOTO JE KĽÚČOVÉ: Používame komunitnú verziu s podporou pre C6
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

; Definícia dosky
board = esp32-c6-devkitc-1
framework = arduino 

; Viac flash pre jednu aplikaciu (bez OTA), aby sa firmware zmestil
board_build.partitions = huge_app.csv

; Rýchlosť
monitor_speed = 115200
upload_speed = 921600

; Nastavenia pre USB (aby fungoval Serial Monitor cez USB-C)
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; Knižnice
lib_deps = 
    bblanchon/ArduinoJson@^7.2.1
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    crankyoldgit/IRremoteESP8266@^2.8.6